SET NAMES utf8mb4;
ALTER TABLE `community_db`.`community` COMMENT = '社区表';
ALTER TABLE `community_db`.`service_item` COMMENT = '服务项目表';
ALTER TABLE `notify_db`.`notify_record` COMMENT = '通知记录表';
ALTER TABLE `order_db`.`order_grab_record` COMMENT = '抢单记录表';
ALTER TABLE `order_db`.`order_status_log` COMMENT = '订单状态日志表';
ALTER TABLE `order_db`.`service_order` COMMENT = '预约单表';
ALTER TABLE `user_db`.`elder_profile` COMMENT = '老人档案表';
ALTER TABLE `user_db`.`family_elder_bind` COMMENT = '亲情号绑定老人表';
ALTER TABLE `user_db`.`user_account` COMMENT = '用户账号表';
ALTER TABLE `user_db`.`user_role` COMMENT = '用户角色表';
ALTER TABLE `volunteer_db`.`volunteer_available_time` COMMENT = '志愿者可服务时间表';
ALTER TABLE `volunteer_db`.`volunteer_profile` COMMENT = '志愿者档案表';
ALTER TABLE `volunteer_db`.`volunteer_time_lock` COMMENT = '志愿者时间锁表';
ALTER TABLE `community_db`.`community` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '社区主键';
ALTER TABLE `community_db`.`community` MODIFY COLUMN `community_id` bigint unsigned NOT NULL COMMENT '社区ID，和主键保持一致或由业务生成';
ALTER TABLE `community_db`.`community` MODIFY COLUMN `community_name` varchar(128) NOT NULL COMMENT '社区名称';
ALTER TABLE `community_db`.`community` MODIFY COLUMN `province` varchar(64) NULL DEFAULT NULL COMMENT '省份';
ALTER TABLE `community_db`.`community` MODIFY COLUMN `city` varchar(64) NULL DEFAULT NULL COMMENT '城市';
ALTER TABLE `community_db`.`community` MODIFY COLUMN `district` varchar(64) NULL DEFAULT NULL COMMENT '区县';
ALTER TABLE `community_db`.`community` MODIFY COLUMN `address` varchar(255) NULL DEFAULT NULL COMMENT '社区详细地址';
ALTER TABLE `community_db`.`community` MODIFY COLUMN `contact_name` varchar(64) NULL DEFAULT NULL COMMENT '社区联系人';
ALTER TABLE `community_db`.`community` MODIFY COLUMN `contact_phone` varchar(20) NULL DEFAULT NULL COMMENT '社区联系电话';
ALTER TABLE `community_db`.`community` MODIFY COLUMN `community_status` tinyint NOT NULL DEFAULT '1' COMMENT '社区状态：1正常，2停用';
ALTER TABLE `community_db`.`community` MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `community_db`.`community` MODIFY COLUMN `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `community_db`.`community` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '逻辑删除：0未删除，1已删除';
ALTER TABLE `community_db`.`service_item` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '服务项目主键';
ALTER TABLE `community_db`.`service_item` MODIFY COLUMN `community_id` bigint unsigned NOT NULL COMMENT '所属社区ID';
ALTER TABLE `community_db`.`service_item` MODIFY COLUMN `item_name` varchar(128) NOT NULL COMMENT '服务项目名称';
ALTER TABLE `community_db`.`service_item` MODIFY COLUMN `item_code` varchar(64) NOT NULL COMMENT '服务项目编码';
ALTER TABLE `community_db`.`service_item` MODIFY COLUMN `item_desc` varchar(512) NULL DEFAULT NULL COMMENT '服务项目说明';
ALTER TABLE `community_db`.`service_item` MODIFY COLUMN `duration_minutes` int NOT NULL DEFAULT '60' COMMENT '默认服务时长，单位分钟';
ALTER TABLE `community_db`.`service_item` MODIFY COLUMN `price_cent` int NOT NULL DEFAULT '0' COMMENT '服务价格，单位分，公益服务可为0';
ALTER TABLE `community_db`.`service_item` MODIFY COLUMN `item_status` tinyint NOT NULL DEFAULT '1' COMMENT '项目状态：1启用，2停用';
ALTER TABLE `community_db`.`service_item` MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `community_db`.`service_item` MODIFY COLUMN `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `community_db`.`service_item` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '逻辑删除：0未删除，1已删除';
ALTER TABLE `notify_db`.`notify_record` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '通知记录主键';
ALTER TABLE `notify_db`.`notify_record` MODIFY COLUMN `community_id` bigint unsigned NOT NULL COMMENT '所属社区ID';
ALTER TABLE `notify_db`.`notify_record` MODIFY COLUMN `business_type` varchar(32) NOT NULL COMMENT '业务类型：ORDER_STATUS订单状态通知';
ALTER TABLE `notify_db`.`notify_record` MODIFY COLUMN `business_id` bigint unsigned NOT NULL COMMENT '业务ID，例如预约单ID';
ALTER TABLE `notify_db`.`notify_record` MODIFY COLUMN `receiver_user_id` bigint unsigned NOT NULL COMMENT '接收人用户ID';
ALTER TABLE `notify_db`.`notify_record` MODIFY COLUMN `receiver_phone` varchar(20) NULL DEFAULT NULL COMMENT '接收人手机号';
ALTER TABLE `notify_db`.`notify_record` MODIFY COLUMN `notify_channel` varchar(32) NOT NULL COMMENT '通知渠道：SMS短信，WECHAT小程序订阅消息，IN_APP站内';
ALTER TABLE `notify_db`.`notify_record` MODIFY COLUMN `notify_title` varchar(128) NOT NULL COMMENT '通知标题';
ALTER TABLE `notify_db`.`notify_record` MODIFY COLUMN `notify_content` varchar(1024) NOT NULL COMMENT '通知内容';
ALTER TABLE `notify_db`.`notify_record` MODIFY COLUMN `notify_status` tinyint NOT NULL DEFAULT '1' COMMENT '通知状态：1待发送，2发送成功，3发送失败';
ALTER TABLE `notify_db`.`notify_record` MODIFY COLUMN `retry_count` int NOT NULL DEFAULT '0' COMMENT '重试次数';
ALTER TABLE `notify_db`.`notify_record` MODIFY COLUMN `next_retry_time` datetime NULL DEFAULT NULL COMMENT '下次重试时间';
ALTER TABLE `notify_db`.`notify_record` MODIFY COLUMN `sent_at` datetime NULL DEFAULT NULL COMMENT '发送成功时间';
ALTER TABLE `notify_db`.`notify_record` MODIFY COLUMN `fail_reason` varchar(255) NULL DEFAULT NULL COMMENT '失败原因';
ALTER TABLE `notify_db`.`notify_record` MODIFY COLUMN `mq_message_id` varchar(128) NULL DEFAULT NULL COMMENT 'MQ消息ID，用于消费幂等';
ALTER TABLE `notify_db`.`notify_record` MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `notify_db`.`notify_record` MODIFY COLUMN `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `notify_db`.`notify_record` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '逻辑删除：0未删除，1已删除';
ALTER TABLE `order_db`.`order_grab_record` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '抢单记录主键';
ALTER TABLE `order_db`.`order_grab_record` MODIFY COLUMN `community_id` bigint unsigned NOT NULL COMMENT '所属社区ID';
ALTER TABLE `order_db`.`order_grab_record` MODIFY COLUMN `order_id` bigint unsigned NOT NULL COMMENT '预约单ID';
ALTER TABLE `order_db`.`order_grab_record` MODIFY COLUMN `order_no` varchar(64) NOT NULL COMMENT '预约单号';
ALTER TABLE `order_db`.`order_grab_record` MODIFY COLUMN `volunteer_user_id` bigint unsigned NOT NULL COMMENT '抢单志愿者用户ID';
ALTER TABLE `order_db`.`order_grab_record` MODIFY COLUMN `grab_status` tinyint NOT NULL COMMENT '抢单结果：1成功，2失败，3重复抢单，4时间冲突';
ALTER TABLE `order_db`.`order_grab_record` MODIFY COLUMN `fail_reason` varchar(255) NULL DEFAULT NULL COMMENT '失败原因';
ALTER TABLE `order_db`.`order_grab_record` MODIFY COLUMN `request_id` varchar(64) NULL DEFAULT NULL COMMENT '请求幂等ID，用于防重复提交';
ALTER TABLE `order_db`.`order_grab_record` MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `order_db`.`order_status_log` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '订单状态日志主键';
ALTER TABLE `order_db`.`order_status_log` MODIFY COLUMN `community_id` bigint unsigned NOT NULL COMMENT '所属社区ID';
ALTER TABLE `order_db`.`order_status_log` MODIFY COLUMN `order_id` bigint unsigned NOT NULL COMMENT '预约单ID';
ALTER TABLE `order_db`.`order_status_log` MODIFY COLUMN `order_no` varchar(64) NOT NULL COMMENT '预约单号';
ALTER TABLE `order_db`.`order_status_log` MODIFY COLUMN `from_status` varchar(32) NULL DEFAULT NULL COMMENT '流转前状态，创建订单时可为空';
ALTER TABLE `order_db`.`order_status_log` MODIFY COLUMN `to_status` varchar(32) NOT NULL COMMENT '流转后状态';
ALTER TABLE `order_db`.`order_status_log` MODIFY COLUMN `operator_user_id` bigint unsigned NULL DEFAULT NULL COMMENT '操作人用户ID，系统操作可为空';
ALTER TABLE `order_db`.`order_status_log` MODIFY COLUMN `operator_role` varchar(32) NULL DEFAULT NULL COMMENT '操作人角色';
ALTER TABLE `order_db`.`order_status_log` MODIFY COLUMN `operate_type` varchar(32) NOT NULL COMMENT '操作类型：CREATE，ASSIGN，GRAB，START，COMPLETE，CANCEL';
ALTER TABLE `order_db`.`order_status_log` MODIFY COLUMN `operate_remark` varchar(255) NULL DEFAULT NULL COMMENT '操作备注';
ALTER TABLE `order_db`.`order_status_log` MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `order_db`.`service_order` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '预约单主键';
ALTER TABLE `order_db`.`service_order` MODIFY COLUMN `community_id` bigint unsigned NOT NULL COMMENT '所属社区ID';
ALTER TABLE `order_db`.`service_order` MODIFY COLUMN `order_no` varchar(64) NOT NULL COMMENT '预约单号，全局唯一';
ALTER TABLE `order_db`.`service_order` MODIFY COLUMN `elder_user_id` bigint unsigned NOT NULL COMMENT '被服务老人用户ID';
ALTER TABLE `order_db`.`service_order` MODIFY COLUMN `creator_user_id` bigint unsigned NOT NULL COMMENT '下单人用户ID，老人本人或亲情号';
ALTER TABLE `order_db`.`service_order` MODIFY COLUMN `creator_role` varchar(32) NOT NULL COMMENT '下单人角色：ELDER，FAMILY';
ALTER TABLE `order_db`.`service_order` MODIFY COLUMN `service_item_id` bigint unsigned NOT NULL COMMENT '服务项目ID';
ALTER TABLE `order_db`.`service_order` MODIFY COLUMN `service_address` varchar(255) NOT NULL COMMENT '服务地址';
ALTER TABLE `order_db`.`service_order` MODIFY COLUMN `service_start_time` datetime NOT NULL COMMENT '预约服务开始时间';
ALTER TABLE `order_db`.`service_order` MODIFY COLUMN `service_end_time` datetime NOT NULL COMMENT '预约服务结束时间';
ALTER TABLE `order_db`.`service_order` MODIFY COLUMN `assign_mode` varchar(32) NOT NULL COMMENT '分配方式：DIRECT指定志愿者，PUBLIC_POOL公共订单池';
ALTER TABLE `order_db`.`service_order` MODIFY COLUMN `specified_volunteer_user_id` bigint unsigned NULL DEFAULT NULL COMMENT '指定的志愿者用户ID，仅DIRECT时有值';
ALTER TABLE `order_db`.`service_order` MODIFY COLUMN `assigned_volunteer_user_id` bigint unsigned NULL DEFAULT NULL COMMENT '最终接单志愿者用户ID';
ALTER TABLE `order_db`.`service_order` MODIFY COLUMN `order_status` varchar(32) NOT NULL COMMENT '订单状态：CREATED待处理，WAITING_GRAB待抢单，ASSIGNED已分配，IN_SERVICE服务中，COMPLETED已完成，CANCELLED已取消';
ALTER TABLE `order_db`.`service_order` MODIFY COLUMN `order_source` varchar(32) NOT NULL DEFAULT 'MINI_APP' COMMENT '订单来源：MINI_APP小程序，STAFF后台';
ALTER TABLE `order_db`.`service_order` MODIFY COLUMN `remark` varchar(512) NULL DEFAULT NULL COMMENT '预约备注';
ALTER TABLE `order_db`.`service_order` MODIFY COLUMN `cancel_reason` varchar(255) NULL DEFAULT NULL COMMENT '取消原因';
ALTER TABLE `order_db`.`service_order` MODIFY COLUMN `grab_deadline` datetime NULL DEFAULT NULL COMMENT '公共池抢单截止时间';
ALTER TABLE `order_db`.`service_order` MODIFY COLUMN `assigned_at` datetime NULL DEFAULT NULL COMMENT '分配或抢单成功时间';
ALTER TABLE `order_db`.`service_order` MODIFY COLUMN `completed_at` datetime NULL DEFAULT NULL COMMENT '完成时间';
ALTER TABLE `order_db`.`service_order` MODIFY COLUMN `cancelled_at` datetime NULL DEFAULT NULL COMMENT '取消时间';
ALTER TABLE `order_db`.`service_order` MODIFY COLUMN `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本号，用于并发更新订单';
ALTER TABLE `order_db`.`service_order` MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `order_db`.`service_order` MODIFY COLUMN `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `order_db`.`service_order` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '逻辑删除：0未删除，1已删除';
ALTER TABLE `user_db`.`elder_profile` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '老人档案主键';
ALTER TABLE `user_db`.`elder_profile` MODIFY COLUMN `community_id` bigint unsigned NOT NULL COMMENT '所属社区ID';
ALTER TABLE `user_db`.`elder_profile` MODIFY COLUMN `user_id` bigint unsigned NOT NULL COMMENT '老人对应的用户账号ID';
ALTER TABLE `user_db`.`elder_profile` MODIFY COLUMN `elder_name` varchar(64) NOT NULL COMMENT '老人姓名';
ALTER TABLE `user_db`.`elder_profile` MODIFY COLUMN `elder_phone` varchar(20) NULL DEFAULT NULL COMMENT '老人联系电话';
ALTER TABLE `user_db`.`elder_profile` MODIFY COLUMN `age` int NULL DEFAULT NULL COMMENT '年龄';
ALTER TABLE `user_db`.`elder_profile` MODIFY COLUMN `address` varchar(255) NULL DEFAULT NULL COMMENT '详细住址';
ALTER TABLE `user_db`.`elder_profile` MODIFY COLUMN `health_note` varchar(512) NULL DEFAULT NULL COMMENT '健康情况备注，例如慢病、行动不便等';
ALTER TABLE `user_db`.`elder_profile` MODIFY COLUMN `emergency_contact_name` varchar(64) NULL DEFAULT NULL COMMENT '紧急联系人姓名';
ALTER TABLE `user_db`.`elder_profile` MODIFY COLUMN `emergency_contact_phone` varchar(20) NULL DEFAULT NULL COMMENT '紧急联系人手机号';
ALTER TABLE `user_db`.`elder_profile` MODIFY COLUMN `profile_status` tinyint NOT NULL DEFAULT '1' COMMENT '档案状态：1正常，2停用';
ALTER TABLE `user_db`.`elder_profile` MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `user_db`.`elder_profile` MODIFY COLUMN `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `user_db`.`elder_profile` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '逻辑删除：0未删除，1已删除';
ALTER TABLE `user_db`.`family_elder_bind` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '亲情号绑定主键';
ALTER TABLE `user_db`.`family_elder_bind` MODIFY COLUMN `community_id` bigint unsigned NOT NULL COMMENT '所属社区ID';
ALTER TABLE `user_db`.`family_elder_bind` MODIFY COLUMN `family_user_id` bigint unsigned NOT NULL COMMENT '亲情号用户ID';
ALTER TABLE `user_db`.`family_elder_bind` MODIFY COLUMN `elder_user_id` bigint unsigned NOT NULL COMMENT '老人用户ID';
ALTER TABLE `user_db`.`family_elder_bind` MODIFY COLUMN `relationship` varchar(32) NOT NULL COMMENT '关系：CHILD子女，SPOUSE配偶，RELATIVE亲属，OTHER其他';
ALTER TABLE `user_db`.`family_elder_bind` MODIFY COLUMN `bind_status` tinyint NOT NULL DEFAULT '1' COMMENT '绑定状态：1待确认，2已绑定，3已拒绝，4已解绑';
ALTER TABLE `user_db`.`family_elder_bind` MODIFY COLUMN `bind_source` varchar(32) NOT NULL DEFAULT 'MINI_APP' COMMENT '绑定来源：MINI_APP小程序，STAFF后台';
ALTER TABLE `user_db`.`family_elder_bind` MODIFY COLUMN `confirmed_at` datetime NULL DEFAULT NULL COMMENT '老人确认绑定时间';
ALTER TABLE `user_db`.`family_elder_bind` MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `user_db`.`family_elder_bind` MODIFY COLUMN `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `user_db`.`family_elder_bind` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '逻辑删除：0未删除，1已删除';
ALTER TABLE `user_db`.`user_account` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '用户账号主键';
ALTER TABLE `user_db`.`user_account` MODIFY COLUMN `community_id` bigint unsigned NOT NULL COMMENT '所属社区ID，社区级平台的数据隔离字段';
ALTER TABLE `user_db`.`user_account` MODIFY COLUMN `phone` varchar(20) NULL DEFAULT NULL COMMENT '登录手机号，微信首次静默登录时可为空，绑定手机号后写入';
ALTER TABLE `user_db`.`user_account` MODIFY COLUMN `open_id` varchar(128) NULL DEFAULT NULL COMMENT '微信小程序openId，同一小程序内唯一';
ALTER TABLE `user_db`.`user_account` MODIFY COLUMN `union_id` varchar(128) NULL DEFAULT NULL COMMENT '微信开放平台unionId，未绑定开放平台时可为空';
ALTER TABLE `user_db`.`user_account` MODIFY COLUMN `password_hash` varchar(255) NULL DEFAULT NULL COMMENT '密码哈希，小程序验证码登录时可以为空';
ALTER TABLE `user_db`.`user_account` MODIFY COLUMN `nickname` varchar(64) NULL DEFAULT NULL COMMENT '用户昵称';
ALTER TABLE `user_db`.`user_account` MODIFY COLUMN `avatar_url` varchar(512) NULL DEFAULT NULL COMMENT '头像地址';
ALTER TABLE `user_db`.`user_account` MODIFY COLUMN `real_name` varchar(64) NULL DEFAULT NULL COMMENT '实名姓名，第一版可为空';
ALTER TABLE `user_db`.`user_account` MODIFY COLUMN `id_card_no` varchar(32) NULL DEFAULT NULL COMMENT '身份证号，建议业务层加密或脱敏存储';
ALTER TABLE `user_db`.`user_account` MODIFY COLUMN `gender` tinyint NOT NULL DEFAULT '0' COMMENT '性别：0未知，1男，2女';
ALTER TABLE `user_db`.`user_account` MODIFY COLUMN `account_status` tinyint NOT NULL DEFAULT '1' COMMENT '账号状态：1正常，2禁用';
ALTER TABLE `user_db`.`user_account` MODIFY COLUMN `current_role` varchar(32) NULL DEFAULT NULL COMMENT '当前启用角色，多身份账号切换时更新';
ALTER TABLE `user_db`.`user_account` MODIFY COLUMN `refresh_token_version` int NOT NULL DEFAULT '0' COMMENT '刷新令牌版本，退出登录或强制下线时递增';
ALTER TABLE `user_db`.`user_account` MODIFY COLUMN `last_login_time` datetime NULL DEFAULT NULL COMMENT '最近登录时间';
ALTER TABLE `user_db`.`user_account` MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `user_db`.`user_account` MODIFY COLUMN `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `user_db`.`user_account` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '逻辑删除：0未删除，1已删除';
ALTER TABLE `user_db`.`user_role` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '用户角色主键';
ALTER TABLE `user_db`.`user_role` MODIFY COLUMN `community_id` bigint unsigned NOT NULL COMMENT '所属社区ID';
ALTER TABLE `user_db`.`user_role` MODIFY COLUMN `user_id` bigint unsigned NOT NULL COMMENT '用户账号ID';
ALTER TABLE `user_db`.`user_role` MODIFY COLUMN `role_code` varchar(32) NOT NULL COMMENT '角色编码：ELDER，FAMILY，VOLUNTEER';
ALTER TABLE `user_db`.`user_role` MODIFY COLUMN `role_status` tinyint NOT NULL DEFAULT '1' COMMENT '角色状态：1正常，2禁用';
ALTER TABLE `user_db`.`user_role` MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `user_db`.`user_role` MODIFY COLUMN `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `user_db`.`user_role` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '逻辑删除：0未删除，1已删除';
ALTER TABLE `volunteer_db`.`volunteer_available_time` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '可服务时间主键';
ALTER TABLE `volunteer_db`.`volunteer_available_time` MODIFY COLUMN `community_id` bigint unsigned NOT NULL COMMENT '所属社区ID';
ALTER TABLE `volunteer_db`.`volunteer_available_time` MODIFY COLUMN `volunteer_user_id` bigint unsigned NOT NULL COMMENT '志愿者用户ID';
ALTER TABLE `volunteer_db`.`volunteer_available_time` MODIFY COLUMN `service_item_id` bigint unsigned NULL DEFAULT NULL COMMENT '可服务项目ID，NULL表示不限服务项目';
ALTER TABLE `volunteer_db`.`volunteer_available_time` MODIFY COLUMN `available_date` date NOT NULL COMMENT '可服务日期';
ALTER TABLE `volunteer_db`.`volunteer_available_time` MODIFY COLUMN `start_time` datetime NOT NULL COMMENT '可服务开始时间';
ALTER TABLE `volunteer_db`.`volunteer_available_time` MODIFY COLUMN `end_time` datetime NOT NULL COMMENT '可服务结束时间';
ALTER TABLE `volunteer_db`.`volunteer_available_time` MODIFY COLUMN `available_status` tinyint NOT NULL DEFAULT '1' COMMENT '状态：1可用，2已锁定，3已取消，4已过期';
ALTER TABLE `volunteer_db`.`volunteer_available_time` MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `volunteer_db`.`volunteer_available_time` MODIFY COLUMN `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `volunteer_db`.`volunteer_available_time` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '逻辑删除：0未删除，1已删除';
ALTER TABLE `volunteer_db`.`volunteer_profile` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '志愿者档案主键';
ALTER TABLE `volunteer_db`.`volunteer_profile` MODIFY COLUMN `community_id` bigint unsigned NOT NULL COMMENT '所属社区ID';
ALTER TABLE `volunteer_db`.`volunteer_profile` MODIFY COLUMN `user_id` bigint unsigned NOT NULL COMMENT '志愿者对应的用户账号ID';
ALTER TABLE `volunteer_db`.`volunteer_profile` MODIFY COLUMN `volunteer_name` varchar(64) NOT NULL COMMENT '志愿者姓名';
ALTER TABLE `volunteer_db`.`volunteer_profile` MODIFY COLUMN `volunteer_phone` varchar(20) NULL DEFAULT NULL COMMENT '志愿者联系电话';
ALTER TABLE `volunteer_db`.`volunteer_profile` MODIFY COLUMN `skill_tags` varchar(255) NULL DEFAULT NULL COMMENT '技能标签，逗号分隔，例如陪诊,助餐,家政';
ALTER TABLE `volunteer_db`.`volunteer_profile` MODIFY COLUMN `service_radius_meter` int NULL DEFAULT NULL COMMENT '可服务半径，单位米';
ALTER TABLE `volunteer_db`.`volunteer_profile` MODIFY COLUMN `profile_status` tinyint NOT NULL DEFAULT '1' COMMENT '档案状态：1待审核，2正常，3停用';
ALTER TABLE `volunteer_db`.`volunteer_profile` MODIFY COLUMN `audit_time` datetime NULL DEFAULT NULL COMMENT '审核通过时间';
ALTER TABLE `volunteer_db`.`volunteer_profile` MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `volunteer_db`.`volunteer_profile` MODIFY COLUMN `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `volunteer_db`.`volunteer_profile` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '逻辑删除：0未删除，1已删除';
ALTER TABLE `volunteer_db`.`volunteer_time_lock` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '志愿者时间锁主键';
ALTER TABLE `volunteer_db`.`volunteer_time_lock` MODIFY COLUMN `community_id` bigint unsigned NOT NULL COMMENT '所属社区ID';
ALTER TABLE `volunteer_db`.`volunteer_time_lock` MODIFY COLUMN `volunteer_user_id` bigint unsigned NOT NULL COMMENT '志愿者用户ID';
ALTER TABLE `volunteer_db`.`volunteer_time_lock` MODIFY COLUMN `order_id` bigint unsigned NOT NULL COMMENT '占用该时间段的预约单ID';
ALTER TABLE `volunteer_db`.`volunteer_time_lock` MODIFY COLUMN `lock_date` date NOT NULL COMMENT '锁定日期';
ALTER TABLE `volunteer_db`.`volunteer_time_lock` MODIFY COLUMN `start_time` datetime NOT NULL COMMENT '锁定开始时间';
ALTER TABLE `volunteer_db`.`volunteer_time_lock` MODIFY COLUMN `end_time` datetime NOT NULL COMMENT '锁定结束时间';
ALTER TABLE `volunteer_db`.`volunteer_time_lock` MODIFY COLUMN `time_slot_key` varchar(64) NOT NULL COMMENT '固定时间槽标识，例如202605041000_202605041100';
ALTER TABLE `volunteer_db`.`volunteer_time_lock` MODIFY COLUMN `lock_status` tinyint NOT NULL DEFAULT '1' COMMENT '锁状态：1已锁定，2已释放';
ALTER TABLE `volunteer_db`.`volunteer_time_lock` MODIFY COLUMN `active_time_slot_key` varchar(64) GENERATED ALWAYS AS ((case when ((`lock_status` = 1) and (`deleted` = 0)) then `time_slot_key` else NULL end)) STORED COMMENT '仅活跃锁参与唯一约束的时间槽';
ALTER TABLE `volunteer_db`.`volunteer_time_lock` MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `volunteer_db`.`volunteer_time_lock` MODIFY COLUMN `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `volunteer_db`.`volunteer_time_lock` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '逻辑删除：0未删除，1已删除';
